### ISSUE TITLE
Refactor: Avoid Passing Controller Context to Service Layer

### ISSUE THREAD

**Issue by lmmendes** [inbox451/inbox451#25]
After reviewing the service implementation, it appears that we're passing the controller's context directly to the service layer. This approach compromises our abstraction boundaries, effectively blending controller and service responsibilities. By injecting the controller's context, we tightly couple the service layer to the specifics of the request lifecycle, which limits where and how the service layer can be reused. This dependency means that services can only function correctly in the context of a controller, restricting flexibility and reducing separation of concerns.

Instead, we should extract the relevant parameters from the request context within the controller and pass only those necessary values to the service layer. This way, our service layer remains decoupled, reusable, and focused solely on the core business logic without knowledge of the request context. 

https://github.com/inbox451/inbox451/blob/a927b348fb456ba8433c0132f6a5cbac1eb0ea95/internal/storage/users.go#L12

cc/ @Jalmeida1994

**Comment by Jalmeida1994** [comment]
Totally agree with the points raised. Passing context.Context around is definitely the Go way for handling cancellations and timeouts, but we’re being a bit lazy by just forwarding the whole request context as-is.

Right now, our service layer ends up with way more info than it needs, creating unnecessary coupling. Ideally, the service layer shouldn’t be aware of request-level details—it just needs what’s relevant to run its logic.

Like you said, we should adjust things so the controller layer pulls out only the essentials (like auth tokens, request IDs, or deadline info) and passes those directly to the service layer. For pure cancellation or timeout handling, we can still use context.Context, but it should be a fresh one derived from the request context instead of the original. This way, we stick to Go’s context pattern without tightly coupling our layers.

Unless it's really a Go way to do things but I would need to investigate a bit more. But by me, let's go for it!

**Comment by lmmendes** [comment]
@Jalmeida1994 I was looking into the authentication concept in general, and with that investigating  how [echo's middleware](https://echo.labstack.com/docs/cookbook/middleware) work.

With that I started running some experiences and was trying the search for a user using it's ID and it was then it struck me that to call the GetUserByID I would need to pass the context, from the request.

**Comment by Jalmeida1994** [comment]
Holding off on #22 (unit test implementation) pending this refactor. The current design passes request context directly through to the storage layer, which creates tight coupling and makes unit testing more complex - we shouldn't need to mock HTTP request context at the storage level.

**Comment by lmmendes** [comment]
Hi @Jalmeida1994 , I just noticed that the `Context`that we are passing is `context.Context` interface and not Echo Context and this has a special meaning.

The `context.Context` interface is a core part of Go's concurrency control and request-scoped data management. 

```go
type Context interface {
    Deadline() (deadline time.Time, ok bool)
    Done() <-chan struct{}
    Err() error
    Value(key any) any
}
```
The main purposes of the Context is:

- Canceling Signal, important then the HTTP connection gets closed for example and we are in the middle of a SQL query, with this we can push the cancel to the SQL server to end the query.
- Deadline management in Go allows you to set a specific time at which a context should expire. This is useful for enforcing timeouts and managing time-sensitive operations and we see this across a bunch of apps with `context.WithDeadline()` 
 and `context.WithTimeout()`
- Request-scoped value propagation, this allows to pass values across the call stack wirthout passing parameters throw methods, we can use this for passing "core" to the entire APP without needing to push it as method parameter for example and can retrieve it from the `Context`, this works also for auth objects for example.
- Resource cleanup, when looking to `ctx.Done()` during long running tasks we can understand if we can free given resources or not.

This said, regarding propagating the context to our service layer we can derive the following benefits of keeping it as-is:

- allows us to propagate the cancellation signals 
- allows us to access context scope values
- allows us to check for timeouts looking at `ctx.Done()` before running a request / query, obviously we don't do this but it's good to know :D

Let's have a 1:1 chat regarding this, I'm going to close this ticket.
